name: grabit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.8.0
  firebase_auth: ^1.0.0
  cloud_firestore: ^3.1.7
  flutter_svg: ^0.22.0
  provider: ^6.0.2
  tuple_dart: ^1.4.2
  google_fonts: ^2.3.2
  tuple: ^2.0.0
  firebase_database: ^9.0.14
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: playerNameScript
      fonts:
        - asset: assets/fonts/playerNameScript.otf
          weight: 700



  assets:
    - assets/HostGame/back.png
    - assets/HostGame/join.png
    - assets/How to play/next_BTN.png
    - assets/How to play/X.png
    - assets/HostGame/host.png
    - assets/Lobby/Info_BTN.png
    - assets/Lobby/+ BTN.png
    - assets/Lobby/Avatar_photo.png
    - assets/Lobby/SignIn_BTN.png
    - assets/HostGame/writingArea.svg
    - assets/HostGame/- btn.svg
    - assets/HostGame/+ btn.png
    - assets/How to play/back.png
    - assets/HostGame/mainHeader.svg
    - assets/Lobby/FriendlyBattle_BTN.png
    - assets/Full_pack.svg
    - WoodenTable.svg
    - nickname.png
    - playButton.png
    - 1.svg
    - 2.svg
    - 3.svg
    - 4.svg
    - 5.svg
    - Full_pack.svg
    - CTAButton.png
    - Background.png
    - 1-BLUE.svg
    - 1-GREEN.svg
    - 1-RED.svg
    - 1-YELLOW.svg

    - 2-BLUE.svg
    - 2-GREEN.svg
    - 2-RED.svg
    - 2-YELLOW.svg

    - 3-BLUE.svg
    - 3-GREEN.svg
    - 3-RED.svg
    - 3-YELLOW.svg

    - 4-BLUE.svg
    - 4-GREEN.svg
    - 4-RED.svg
    - 4-YELLOW.svg

    - 5-BLUE.svg
    - 5-GREEN.svg
    - 5-RED.svg
    - 5-YELLOW.svg

    - 6-BLUE.svg
    - 6-GREEN.svg
    - 6-RED.svg
    - 6-YELLOW.svg

    - 7-BLUE.svg
    - 7-GREEN.svg
    - 7-RED.svg
    - 7-YELLOW.svg

    - 8-BLUE.svg
    - 8-GREEN.svg
    - 8-RED.svg
    - 8-YELLOW.svg

    - 9-BLUE.svg
    - 9-GREEN.svg
    - 9-RED.svg
    - 9-YELLOW.svg

    - 10-BLUE.svg
    - 10-GREEN.svg
    - 10-RED.svg
    - 10-YELLOW.svg

    - 11-BLUE.svg
    - 11-GREEN.svg
    - 11-RED.svg
    - 11-YELLOW.svg

    - 12-BLUE.svg
    - 12-GREEN.svg
    - 12-RED.svg
    - 12-YELLOW.svg

    - 13-BLUE.svg
    - 13-GREEN.svg
    - 13-RED.svg
    - 13-YELLOW.svg

    - 14-BLUE.svg
    - 14-GREEN.svg
    - 14-RED.svg
    - 14-YELLOW.svg

    - 15-BLUE.svg
    - 15-GREEN.svg
    - 15-RED.svg
    - 15-YELLOW.svg

    - 16-BLUE.svg
    - 16-GREEN.svg
    - 16-RED.svg
    - 16-YELLOW.svg

    - 17-BLUE.svg
    - 17-GREEN.svg
    - 17-RED.svg
    - 17-YELLOW.svg

    - 18-BLUE.svg
    - 18-GREEN.svg
    - 18-RED.svg
    - 18-YELLOW.svg

    - Special_card1.svg
    - Special_card2.svg
    - Special_card3.svg


  #-
